---
- name: "WordPress Server: Install Nginx and PHP 5.5"
  hosts: web
  remote_user: root
  # sudo: yes

  roles:
    - common
    - { role: mariadb, when "'development' in group_names" }
    - php-55
    - nginx
    - git
    - composer
    - { role: dev-tools, when: "'development' not in group_names" }
    - wp-cli
    - { role: capistrano-setup, when: "'development' not in group_names" }
    - wordpress-sites
